name: Playwright Tests
on: [push, pull_request] 

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.55.0-focal  
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npx playwright test
